<?php

return array(

    'FIELD_NAME' => array(

        'catid' => '分类ID',
        'catname' => '分类名',
        'itemid' => '商品ID',
        'itemname' => '商品名',
        'price' => '商品价格',
        'order_price' => '订单商品价格',
        'inventory' => '商品库存',
        'view' => '浏览量',
        'volume' => '销量',
        'item_status' => '商品状态',
        'item_isdel' => '商品是否删除',
        'typeid' => '类目ID',
        'typename' => '类目名',
        'orderid' => '订单ID',
        'tradeid' => '发货单ID',
        'uid' => '用户ID',
        'user_isdel' => '用户是否删除',
        'unread' => '用户未读消息',
        'productid' => '产品ID',
        'point' => '积分',
        'num' => '商品数量',
        'uname' => '用户名',
        'trade_status' => '发货单状态',
        'totalfee' => '订单总费用',
        'typeid' => '类目ID',
        'order_itemname' => '订单商品名',
        'order_isdel' => '订单是否删除',
        'receiver_name' => '收货人',
        'receiver_address' => '收获地址',
        'receiver_link' => '收获联系方式',
        'sendtime' => '预定发货时间',
        'payment' => '支付方式',
        'paytime' => '支付时间',
        'posttime' => '发货时间',
        'deli_status' => '送货状态',
        'deli_man' => '送货员ID',
        'spec_name' => '规格名',
        'specval_name' => '规格值',
        'receiver' => '收货人',
        'address' => '收货地址',
        'addressid' => '收货地址ID',
        'link' => '联系电话',
        'adminid' => '管理员ID',
        'admin_isdel' => '管理员是否删除',
        'admin_email'=>'管理员邮箱',
        'role'=>'管理员角色',
        'admin_name'=>'管理员姓名',
        'admin_uname'=>'管理员用户名',
        'email'=>'用户邮箱',
        'deli_name'=>'送货员名',
        'deli_uname'=>'送货员账号',
        'deli_email'=>'送货员邮箱',
        'deli_id'=>'送货员ID',
        'deli_isdel'=>'送货员是否删除',
        'regip'=>'用户注册IP',
        'user_regtime'=>'用户注册时间',
        'user_lasttime'=>'用户最后登陆时间',
        'discount'=>'打折活动',
        
    ), 

);
